### ISSUE TITLE
No Method Error:

### ISSUE THREAD

**Issue by DeArchiTech** [ryancwong8/blunt_api#1]
Not too sure if I am not calling it properly, but I am getting internal server error???

NULL LIMIT 1
Unpermitted parameter: seekingprofile
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.5ms)

NoMethodError (undefined method `update' for nil:NilClass):
  app/controllers/api/v1/users_controller.rb:55:in`get_filtered_users'

```
  def get_filtered_users
    user = current_user
        #No method error?
    user.update(user_params)
    user.SeekingProfile.update(params.require(:user).permit(:seekingprofile_attributes => [:maxSeekDistance, :minSeekDistance]))
    distance = user.SeekingProfile.maxSeekDistance - user.SeekingProfile.minSeekDistance
    @users = User.within(distance, :units => :miles, :origin => [user.latitude, user.longitude]).by_distance(:origin => [user.latitude, user.longitude]).where.not(facebook_id: user.facebook_id)
    render :json => @users
  end
```

See if this helps

http://stackoverflow.com/questions/21927567/undefined-method-update-for-nil-class

@ryancwong8

**Comment by ryanchristopherwong8** [comment]
Hey noobiehacker,

I assume this error is occurring because user is null. This user is assigned to null because you must send authorization token in headers with the request. I will implement a more informative error message.

Ryan

**Comment by DeArchiTech** [comment]
Hey Ryan, thanks for looking into it~

I think the following line might need modification

`user.SeekingProfile.update(params.require(:user).permit(:seekingprofile_attributes => [:maxSeekDistance, :minSeekDistance]))`

I debugged and found out user_params has no seekingprofile, minSeekDistance or maxSeekDistance, causing the app to crash on this line. 

`distance = user.SeekingProfile.maxSeekDistance - user.SeekingProfile.minSeekDistance
`
 Is it because my Json Payload not set correctly or perhaps we need to set the permit nested hash a bit differently??

**Comment by ryanchristopherwong8** [comment]
Hi noobiehacker, 

I updated the apiary documentation to fix capitalization errors within the request json. Sorry for the confusion, Thanks!
